name=Ackorduino
version=1.0.0
author=Josh Nishikawa
maintainer=Josh Nishikawa
sentence=MIDI Chord Analyzer library for Arduino and Teensy.
paragraph=Analyzes active MIDI notes and identifies root note, chords, suffixes, and slash bass inversions with custom display support.
category=Other
url=https://github.com/joshnishikawa/Ackorduino
architectures=*
includes=ChordAnalyzer.h
