; PlatformIO & Arduino IDE Compatible Configuration for Teensy 3.6
[platformio]
src_dir = .

[env:teensy36]
platform = teensy
board = teensy36
framework = arduino
build_flags = 
    -D USB_MIDI
lib_deps =
    MIDI Library
    Adafruit GFX Library
    Adafruit SSD1306